//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrecosaAppCrm.ServiceSMS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSMS.wsAPISmsCorpSoap")]
    public interface wsAPISmsCorpSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/enviarBulkSmsXMLHN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CrecosaAppCrm.ServiceSMS.clRespuestaBulkSms enviarBulkSmsXMLHN(string usuario, string contrasena, string Mensajes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/enviarBulkSmsXMLHN", ReplyAction="*")]
        System.Threading.Tasks.Task<CrecosaAppCrm.ServiceSMS.clRespuestaBulkSms> enviarBulkSmsXMLHNAsync(string usuario, string contrasena, string Mensajes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/enviarBulkSmsXMLNC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CrecosaAppCrm.ServiceSMS.clRespuestaBulkSms enviarBulkSmsXMLNC(string usuario, string contrasena, string Mensajes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/enviarBulkSmsXMLNC", ReplyAction="*")]
        System.Threading.Tasks.Task<CrecosaAppCrm.ServiceSMS.clRespuestaBulkSms> enviarBulkSmsXMLNCAsync(string usuario, string contrasena, string Mensajes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/enviarBulkSmsXMLPN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CrecosaAppCrm.ServiceSMS.clRespuestaBulkSms enviarBulkSmsXMLPN(string usuario, string contrasena, string Mensajes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/enviarBulkSmsXMLPN", ReplyAction="*")]
        System.Threading.Tasks.Task<CrecosaAppCrm.ServiceSMS.clRespuestaBulkSms> enviarBulkSmsXMLPNAsync(string usuario, string contrasena, string Mensajes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/enviarBulkSmsXMLGT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CrecosaAppCrm.ServiceSMS.clRespuestaBulkSms enviarBulkSmsXMLGT(string usuario, string contrasena, string Mensajes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/enviarBulkSmsXMLGT", ReplyAction="*")]
        System.Threading.Tasks.Task<CrecosaAppCrm.ServiceSMS.clRespuestaBulkSms> enviarBulkSmsXMLGTAsync(string usuario, string contrasena, string Mensajes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/enviarBulkSmsXMLCR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CrecosaAppCrm.ServiceSMS.clRespuestaBulkSms enviarBulkSmsXMLCR(string usuario, string contrasena, string Mensajes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/enviarBulkSmsXMLCR", ReplyAction="*")]
        System.Threading.Tasks.Task<CrecosaAppCrm.ServiceSMS.clRespuestaBulkSms> enviarBulkSmsXMLCRAsync(string usuario, string contrasena, string Mensajes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/enviarBulkSmsXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CrecosaAppCrm.ServiceSMS.clRespuestaBulkSms enviarBulkSmsXML(string usuario, string contrasena, string Mensajes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/enviarBulkSmsXML", ReplyAction="*")]
        System.Threading.Tasks.Task<CrecosaAppCrm.ServiceSMS.clRespuestaBulkSms> enviarBulkSmsXMLAsync(string usuario, string contrasena, string Mensajes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/enviarBulkSms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CrecosaAppCrm.ServiceSMS.clRespuestaBulkSms enviarBulkSms(string usuario, string contrasena, CrecosaAppCrm.ServiceSMS.clMensajes[] Mensajes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/enviarBulkSms", ReplyAction="*")]
        System.Threading.Tasks.Task<CrecosaAppCrm.ServiceSMS.clRespuestaBulkSms> enviarBulkSmsAsync(string usuario, string contrasena, CrecosaAppCrm.ServiceSMS.clMensajes[] Mensajes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/enviarSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CrecosaAppCrm.ServiceSMS.clRespuesta enviarSMS(string usuario, string contrasena, string numero, string mensaje, string remitente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/enviarSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<CrecosaAppCrm.ServiceSMS.clRespuesta> enviarSMSAsync(string usuario, string contrasena, string numero, string mensaje, string remitente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/enviarSMSEsp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CrecosaAppCrm.ServiceSMS.clRespuesta enviarSMSEsp(string user, string password, string sessionid, string to, string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/enviarSMSEsp", ReplyAction="*")]
        System.Threading.Tasks.Task<CrecosaAppCrm.ServiceSMS.clRespuesta> enviarSMSEspAsync(string user, string password, string sessionid, string to, string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/confirmacionSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CrecosaAppCrm.ServiceSMS.clConfirmacionSMS confirmacionSMS(string usuario, string contrasena, string Referencias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/confirmacionSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<CrecosaAppCrm.ServiceSMS.clConfirmacionSMS> confirmacionSMSAsync(string usuario, string contrasena, string Referencias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RespuestaSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CrecosaAppCrm.ServiceSMS.clRespuestasSMS RespuestaSMS(string usuario, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RespuestaSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<CrecosaAppCrm.ServiceSMS.clRespuestasSMS> RespuestaSMSAsync(string usuario, string contrasena);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clRespuestaBulkSms : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoEstadoField;
        
        private bool esEnvioExitosoField;
        
        private string mensajeRespuestaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int codigoEstado {
            get {
                return this.codigoEstadoField;
            }
            set {
                this.codigoEstadoField = value;
                this.RaisePropertyChanged("codigoEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool esEnvioExitoso {
            get {
                return this.esEnvioExitosoField;
            }
            set {
                this.esEnvioExitosoField = value;
                this.RaisePropertyChanged("esEnvioExitoso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MensajeRespuesta {
            get {
                return this.mensajeRespuestaField;
            }
            set {
                this.mensajeRespuestaField = value;
                this.RaisePropertyChanged("MensajeRespuesta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clListaRespuestas : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private string remitenteField;
        
        private string destinatarioField;
        
        private string mensajeField;
        
        private System.DateTime fechaIngresoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string remitente {
            get {
                return this.remitenteField;
            }
            set {
                this.remitenteField = value;
                this.RaisePropertyChanged("remitente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string destinatario {
            get {
                return this.destinatarioField;
            }
            set {
                this.destinatarioField = value;
                this.RaisePropertyChanged("destinatario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime fechaIngreso {
            get {
                return this.fechaIngresoField;
            }
            set {
                this.fechaIngresoField = value;
                this.RaisePropertyChanged("fechaIngreso");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clRespuestasSMS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoEstadoField;
        
        private string mensajeRespuestaField;
        
        private clListaRespuestas[] listaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int codigoEstado {
            get {
                return this.codigoEstadoField;
            }
            set {
                this.codigoEstadoField = value;
                this.RaisePropertyChanged("codigoEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MensajeRespuesta {
            get {
                return this.mensajeRespuestaField;
            }
            set {
                this.mensajeRespuestaField = value;
                this.RaisePropertyChanged("MensajeRespuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public clListaRespuestas[] lista {
            get {
                return this.listaField;
            }
            set {
                this.listaField = value;
                this.RaisePropertyChanged("lista");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clListaEnvios : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int referenciaField;
        
        private string destinoField;
        
        private string senderIdField;
        
        private string estadoField;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
                this.RaisePropertyChanged("referencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string destino {
            get {
                return this.destinoField;
            }
            set {
                this.destinoField = value;
                this.RaisePropertyChanged("destino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string senderId {
            get {
                return this.senderIdField;
            }
            set {
                this.senderIdField = value;
                this.RaisePropertyChanged("senderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clConfirmacionSMS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoEstadoField;
        
        private string mensajeRespuestaField;
        
        private clListaEnvios[] listaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int codigoEstado {
            get {
                return this.codigoEstadoField;
            }
            set {
                this.codigoEstadoField = value;
                this.RaisePropertyChanged("codigoEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MensajeRespuesta {
            get {
                return this.mensajeRespuestaField;
            }
            set {
                this.mensajeRespuestaField = value;
                this.RaisePropertyChanged("MensajeRespuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public clListaEnvios[] lista {
            get {
                return this.listaField;
            }
            set {
                this.listaField = value;
                this.RaisePropertyChanged("lista");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clRespuesta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoEstadoField;
        
        private bool esEnvioExitosoField;
        
        private string mensajeRespuestaField;
        
        private int referenciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int codigoEstado {
            get {
                return this.codigoEstadoField;
            }
            set {
                this.codigoEstadoField = value;
                this.RaisePropertyChanged("codigoEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool esEnvioExitoso {
            get {
                return this.esEnvioExitosoField;
            }
            set {
                this.esEnvioExitosoField = value;
                this.RaisePropertyChanged("esEnvioExitoso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MensajeRespuesta {
            get {
                return this.mensajeRespuestaField;
            }
            set {
                this.mensajeRespuestaField = value;
                this.RaisePropertyChanged("MensajeRespuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
                this.RaisePropertyChanged("referencia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clMensajes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroField;
        
        private string mensajeField;
        
        private string remitenteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string remitente {
            get {
                return this.remitenteField;
            }
            set {
                this.remitenteField = value;
                this.RaisePropertyChanged("remitente");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsAPISmsCorpSoapChannel : CrecosaAppCrm.ServiceSMS.wsAPISmsCorpSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsAPISmsCorpSoapClient : System.ServiceModel.ClientBase<CrecosaAppCrm.ServiceSMS.wsAPISmsCorpSoap>, CrecosaAppCrm.ServiceSMS.wsAPISmsCorpSoap {
        
        public wsAPISmsCorpSoapClient() {
        }
        
        public wsAPISmsCorpSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsAPISmsCorpSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsAPISmsCorpSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsAPISmsCorpSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CrecosaAppCrm.ServiceSMS.clRespuestaBulkSms enviarBulkSmsXMLHN(string usuario, string contrasena, string Mensajes) {
            return base.Channel.enviarBulkSmsXMLHN(usuario, contrasena, Mensajes);
        }
        
        public System.Threading.Tasks.Task<CrecosaAppCrm.ServiceSMS.clRespuestaBulkSms> enviarBulkSmsXMLHNAsync(string usuario, string contrasena, string Mensajes) {
            return base.Channel.enviarBulkSmsXMLHNAsync(usuario, contrasena, Mensajes);
        }
        
        public CrecosaAppCrm.ServiceSMS.clRespuestaBulkSms enviarBulkSmsXMLNC(string usuario, string contrasena, string Mensajes) {
            return base.Channel.enviarBulkSmsXMLNC(usuario, contrasena, Mensajes);
        }
        
        public System.Threading.Tasks.Task<CrecosaAppCrm.ServiceSMS.clRespuestaBulkSms> enviarBulkSmsXMLNCAsync(string usuario, string contrasena, string Mensajes) {
            return base.Channel.enviarBulkSmsXMLNCAsync(usuario, contrasena, Mensajes);
        }
        
        public CrecosaAppCrm.ServiceSMS.clRespuestaBulkSms enviarBulkSmsXMLPN(string usuario, string contrasena, string Mensajes) {
            return base.Channel.enviarBulkSmsXMLPN(usuario, contrasena, Mensajes);
        }
        
        public System.Threading.Tasks.Task<CrecosaAppCrm.ServiceSMS.clRespuestaBulkSms> enviarBulkSmsXMLPNAsync(string usuario, string contrasena, string Mensajes) {
            return base.Channel.enviarBulkSmsXMLPNAsync(usuario, contrasena, Mensajes);
        }
        
        public CrecosaAppCrm.ServiceSMS.clRespuestaBulkSms enviarBulkSmsXMLGT(string usuario, string contrasena, string Mensajes) {
            return base.Channel.enviarBulkSmsXMLGT(usuario, contrasena, Mensajes);
        }
        
        public System.Threading.Tasks.Task<CrecosaAppCrm.ServiceSMS.clRespuestaBulkSms> enviarBulkSmsXMLGTAsync(string usuario, string contrasena, string Mensajes) {
            return base.Channel.enviarBulkSmsXMLGTAsync(usuario, contrasena, Mensajes);
        }
        
        public CrecosaAppCrm.ServiceSMS.clRespuestaBulkSms enviarBulkSmsXMLCR(string usuario, string contrasena, string Mensajes) {
            return base.Channel.enviarBulkSmsXMLCR(usuario, contrasena, Mensajes);
        }
        
        public System.Threading.Tasks.Task<CrecosaAppCrm.ServiceSMS.clRespuestaBulkSms> enviarBulkSmsXMLCRAsync(string usuario, string contrasena, string Mensajes) {
            return base.Channel.enviarBulkSmsXMLCRAsync(usuario, contrasena, Mensajes);
        }
        
        public CrecosaAppCrm.ServiceSMS.clRespuestaBulkSms enviarBulkSmsXML(string usuario, string contrasena, string Mensajes) {
            return base.Channel.enviarBulkSmsXML(usuario, contrasena, Mensajes);
        }
        
        public System.Threading.Tasks.Task<CrecosaAppCrm.ServiceSMS.clRespuestaBulkSms> enviarBulkSmsXMLAsync(string usuario, string contrasena, string Mensajes) {
            return base.Channel.enviarBulkSmsXMLAsync(usuario, contrasena, Mensajes);
        }
        
        public CrecosaAppCrm.ServiceSMS.clRespuestaBulkSms enviarBulkSms(string usuario, string contrasena, CrecosaAppCrm.ServiceSMS.clMensajes[] Mensajes) {
            return base.Channel.enviarBulkSms(usuario, contrasena, Mensajes);
        }
        
        public System.Threading.Tasks.Task<CrecosaAppCrm.ServiceSMS.clRespuestaBulkSms> enviarBulkSmsAsync(string usuario, string contrasena, CrecosaAppCrm.ServiceSMS.clMensajes[] Mensajes) {
            return base.Channel.enviarBulkSmsAsync(usuario, contrasena, Mensajes);
        }
        
        public CrecosaAppCrm.ServiceSMS.clRespuesta enviarSMS(string usuario, string contrasena, string numero, string mensaje, string remitente) {
            return base.Channel.enviarSMS(usuario, contrasena, numero, mensaje, remitente);
        }
        
        public System.Threading.Tasks.Task<CrecosaAppCrm.ServiceSMS.clRespuesta> enviarSMSAsync(string usuario, string contrasena, string numero, string mensaje, string remitente) {
            return base.Channel.enviarSMSAsync(usuario, contrasena, numero, mensaje, remitente);
        }
        
        public CrecosaAppCrm.ServiceSMS.clRespuesta enviarSMSEsp(string user, string password, string sessionid, string to, string msg) {
            return base.Channel.enviarSMSEsp(user, password, sessionid, to, msg);
        }
        
        public System.Threading.Tasks.Task<CrecosaAppCrm.ServiceSMS.clRespuesta> enviarSMSEspAsync(string user, string password, string sessionid, string to, string msg) {
            return base.Channel.enviarSMSEspAsync(user, password, sessionid, to, msg);
        }
        
        public CrecosaAppCrm.ServiceSMS.clConfirmacionSMS confirmacionSMS(string usuario, string contrasena, string Referencias) {
            return base.Channel.confirmacionSMS(usuario, contrasena, Referencias);
        }
        
        public System.Threading.Tasks.Task<CrecosaAppCrm.ServiceSMS.clConfirmacionSMS> confirmacionSMSAsync(string usuario, string contrasena, string Referencias) {
            return base.Channel.confirmacionSMSAsync(usuario, contrasena, Referencias);
        }
        
        public CrecosaAppCrm.ServiceSMS.clRespuestasSMS RespuestaSMS(string usuario, string contrasena) {
            return base.Channel.RespuestaSMS(usuario, contrasena);
        }
        
        public System.Threading.Tasks.Task<CrecosaAppCrm.ServiceSMS.clRespuestasSMS> RespuestaSMSAsync(string usuario, string contrasena) {
            return base.Channel.RespuestaSMSAsync(usuario, contrasena);
        }
    }
}
