jQuery(document).ready(function(){init();});Date.isLeapYear=function(year){return(((year%4===0)&&(year%100!==0))||(year%400===0));};Date.getDaysInMonth=function(year,month){return[31,(Date.isLeapYear(year)?29:28),31,30,31,30,31,31,30,31,30,31][month];};Date.prototype.isLeapYear=function(){var y=this.getFullYear();return(((y%4===0)&&(y%100!==0))||(y%400===0));};Date.prototype.getDaysInMonth=function(){return Date.getDaysInMonth(this.getFullYear(),this.getMonth());};Date.prototype.addMonths=function(value){var n=this.getDate();this.setDate(1);this.setMonth(this.getMonth()+value);this.setDate(Math.min(n,this.getDaysInMonth()));return this;};function setAmountFormat(value){return"U$ "+value.toFixed(2).replace(/(\d)(?=(\d{3})+\.)/g,"$1,").toString();}
function getValue(id){return document.getElementById(id).value;}
function getFloat(id){var value=parseFloat(getValue(id));return!isNaN(value)?value:parseFloat("0");}
function getInteger(id){return parseInt(getValue(id));}
function setValue(id,value){document.getElementById(id).value=value;}
function setText(id,value){jQuery("#"+id).text("U$ "+value);}
function getParseFloat(value){if((typeof value=="string"||value instanceof String)&&value!=""){value=value.toString().replace("US$").replace("U$").replace("$","").replace("%","").replace(",","");}
if(value==""||isNaN(value)){return 0;}
return parseFloat(value);}
var rates=[[{min:2500,max:50000,apr:25}],[{min:5000,max:10000,apr:33.96}],[{min:100,max:10000,apr:33.96}],[{min:100,max:2000,apr:50},{min:2001,max:3000,apr:47},{min:3001,max:4000,apr:44},{min:4001,max:5000,apr:41},{min:5001,max:10000,apr:23}],[{min:100,max:10000,apr:39.96}],[{min:1500,max:2000,apr:50},{min:2001,max:3000,apr:47},{min:3001,max:4000,apr:44},{min:4001,max:5000,apr:41},{min:5001,max:7000,apr:23},{min:7001,max:10000,apr:23}],[{min:10001,max:50000,apr:25}],[{min:2500,max:25000,apr:30}]];function init(){jQuery("#amount").change(function(){var product=jQuery("#product").val();if(setApr(product)){generatePlan();}});jQuery("#product").change(function(){var product=jQuery("#product").val();if(setApr(product)){generatePlan();}});jQuery(document).on("change",".tasaAnual",function(){populateTableMora();});jQuery(document).on("change",".tasaAnual",function(){populateTableMora();});jQuery(document).on("change",".diasMora",function(){populateTableMora();});}
function setApr(index){var amount=getFloat("amount");var flag=false;if(isNaN(amount)){return false;}
index=index-1;var rate=rates[index];if(Object.keys(rate).length==1){var minvalue=rate[0].min;var maxvalue=rate[0].max;if(evaluateApr(amount,rate[0].min,rate[0].max,rate[0].apr)){flag=true;}else{showErrorMesagge(minvalue,maxvalue,index);}}
if(Object.keys(rate).length>1){var minvalue=rate[0].min;var maxvalue=rate[Object.keys(rate).length-1].max;for(var i=0;i<Object.keys(rate).length;i++){if(evaluateApr(amount,rate[i].min,rate[i].max,rate[i].apr)){flag=true;break;}}
if(flag==false){showErrorMesagge(minvalue,maxvalue,index);}}
return flag;}
function evaluateApr(amount,min,max,apr){var bool=false;if(amount>=min&&amount<=max){setValue("apr",apr+"%");hideErrorMesagge();bool=true;}
return bool;}
function generatePlan(){if(!validateAmount()){showErrorMesagge(0,0);return false;}
if(!validateTerm()){jQuery("#message").text("El plazo introducido es inv\u00E1lido.");jQuery("#message").show();jQuery("#asterikterm").show();jQuery("#term").focus();return false;}
var type=document.querySelector('input[name="tipo-cuota"]:checked').value;if(type=="decreciente"){generarCuotaDecreciente();}else{if(type=="nivelada"){generarCuotaNivelada();}}
hideErrorMesagge();}
function generarCuotaDecreciente(){var amount=getFloat("amount");var term=getInteger("term");var apr=getFloat("apr");var dpr=((apr / 100)/ 360).toFixed(9);var mpr=(apr / 12);var tcea=0;var charges=getFloat("cargos");var table=document.getElementById("payment-plan");var row,cell;table.style.height="auto";for(var i=table.rows.length-1;i>=1;i--){table.deleteRow(i);}
var paymentDate,currentDate=new Date(),initialDate=new Date(currentDate.getFullYear(),currentDate.getMonth(),currentDate.getDate());var paymentDate=initialDate,previousDate=null,days=0,balance=amount;var principal=0,interest=0,payment=0,insurance=0,totalPayment=0;setValue("payment",getFormattedNumber(getPMT((mpr / 100),term,amount).toFixed(2)*-1));table.innerHTML="<thead><th>No. Cuota</th><th>D&iacuteas</th><th>Fecha de pago</th><th>Capital</th><th>Intereses</th><th>Cuota</th><th>Seguros</th><th>Cargos</th><th>Total Pago</th><th>Saldo</th></thead>";var comisiones=getFloat("comisiones");var gastosLegales=getFloat("gasto-legal");var irrData=[(amount*-1)+comisiones+gastosLegales];for(var i=0;i<term;i++){previousDate=new Date(paymentDate.getFullYear(),paymentDate.getMonth(),paymentDate.getDate());paymentDate.addMonths(1);days=(paymentDate-previousDate)/(1000*60*60*24);principal=amount / term;interest=(balance*(days*dpr));payment=parseFloat(principal)+parseFloat(interest);insurance=getInsurance(balance,interest,amount,payment);totalPayment=parseFloat(payment)+parseFloat(insurance)+parseFloat(charges);balance=balance-principal;row=table.insertRow(table.rows.length);cell=row.insertCell(0);cell.align="center";cell.innerHTML=i+1;cell=row.insertCell(1);cell.align="center";cell.innerHTML=days;cell=row.insertCell(2);cell.align="center";cell.innerHTML=paymentDate.toLocaleDateString("en-GB");cell=row.insertCell(3);cell.align="right";cell.className="x-amount";cell.innerHTML=getMoney(principal.toFixed(2));cell=row.insertCell(4);cell.align="right";cell.className="x-amount";cell.innerHTML=getMoney(interest.toFixed(2));cell=row.insertCell(5);cell.align="right";cell.className="x-amount";cell.innerHTML=getMoney(payment.toFixed(2));if(i==0){setText("payment-value",payment.toFixed(2));}
cell=row.insertCell(6);cell.align="center";cell.innerHTML=getMoney(insurance.toFixed(2));cell=row.insertCell(7);cell.align="center";cell.innerHTML=getMoney(charges.toFixed(2));cell=row.insertCell(8);cell.align="right";cell.className="x-amount";cell.innerHTML=getMoney(totalPayment.toFixed(2));cell=row.insertCell(9);cell.align="right";cell.className="x-amount";cell.innerHTML=getMoney(balance.toFixed(2));irrData.push(parseFloat(totalPayment.toFixed(2)));}
tcea=getIRR(irrData);setValue("tcea",(tcea*12).toFixed(2)+"%");document.getElementById("button-mora").style.display="block";}
function generarCuotaNivelada(){var amount=getFloat("amount");var term=getInteger("term");var apr=getFloat("apr");var dpr=((apr / 100)/ 360).toFixed(9);var mpr=(apr / 12);var tcea=0;var charges=getFloat("cargos");var table=document.getElementById("payment-plan");var row,cell;table.style.height="auto";for(var i=table.rows.length-1;i>=1;i--){table.deleteRow(i);}
var paymentDate,currentDate=new Date(),initialDate=new Date(currentDate.getFullYear(),currentDate.getMonth(),currentDate.getDate());var paymentDate=initialDate,previousDate=null,days=0,balance=amount;var principal=0,interest=0,payment=getAdjustedPayment(amount,term,apr,dpr,(getPMT((mpr / 100),term,amount).toFixed(2)*-1)),insurance=0,totalPayment=0;setValue("payment",getFormattedNumber(payment.toFixed(2)));setText("payment-value",getFormattedNumber(payment.toFixed(2)));table.innerHTML="<thead><th>No. Cuota</th><th>D&iacuteas</th><th>Fecha de pago</th><th>Capital</th><th>Intereses</th><th>Cuota</th><th>Seguros</th><th>Cargos</th><th>Total Pago</th><th>Saldo</th></thead>";var comisiones=getFloat("comisiones");var gastosLegales=getFloat("gasto-legal");var irrData=[(amount*-1)+comisiones+gastosLegales];for(var i=0;i<term;i++){previousDate=new Date(paymentDate.getFullYear(),paymentDate.getMonth(),paymentDate.getDate());paymentDate.addMonths(1);days=(paymentDate-previousDate)/(1000*60*60*24);interest=(balance*(days*dpr));principal=payment-interest;insurance=getInsurance(balance,interest,amount,payment);totalPayment=parseFloat(payment)+parseFloat(insurance)+parseFloat(charges);balance=balance-principal;row=table.insertRow(table.rows.length);cell=row.insertCell(0);cell.align="center";cell.innerHTML=i+1;cell=row.insertCell(1);cell.align="center";cell.innerHTML=days;cell=row.insertCell(2);cell.align="center";cell.innerHTML=paymentDate.toLocaleDateString("en-GB");cell=row.insertCell(3);cell.align="right";cell.className="x-amount";cell.innerHTML=getMoney(principal.toFixed(2));cell=row.insertCell(4);cell.align="right";cell.className="x-amount";cell.innerHTML=getMoney(interest.toFixed(2));cell=row.insertCell(5);cell.align="right";cell.className="x-amount";cell.innerHTML=getMoney(payment.toFixed(2));cell=row.insertCell(6);cell.align="center";cell.innerHTML=getMoney(insurance.toFixed(2));cell=row.insertCell(7);cell.align="center";cell.innerHTML=getMoney(charges.toFixed(2));cell=row.insertCell(8);cell.align="right";cell.className="x-amount";cell.innerHTML=getMoney(totalPayment.toFixed(2));cell=row.insertCell(9);cell.align="right";cell.className="x-amount";cell.innerHTML=getMoney(balance.toFixed(2));irrData.push(parseFloat(totalPayment.toFixed(2)));}
tcea=getIRR(irrData);setValue("tcea",(tcea*12).toFixed(2)+"%");document.getElementById("button-mora").style.display="block";}
function getAdjustedPayment(amount,term,apr,dpr,payment){var balance=0;var factor=0.0001;var count=0;var flag=0;do{count=count+1;if(balance>0){payment+=factor;}else{if(balance<0){payment-=factor;}}
balance=getBalance(amount,term,apr,dpr,payment);flag=parseFloat(Math.abs(balance).toFixed(4).substr(0,5));}while(flag>0.001);return payment;}
function getBalance(amount,term,apr,dpr,payment){var paymentDate,currentDate=new Date(),initialDate=new Date(currentDate.getFullYear(),currentDate.getMonth(),currentDate.getDate());var paymentDate=initialDate,previousDate=null,days=0,balance=amount;var principal=0,interest=0;for(var i=0;i<term;i++){previousDate=new Date(paymentDate.getFullYear(),paymentDate.getMonth(),paymentDate.getDate());paymentDate.addMonths(1);days=(paymentDate-previousDate)/(1000*60*60*24);interest=(balance*(days*dpr));principal=payment-interest;balance=balance-principal;}
return balance;}
function percentage(num,per){return(num/100)*per;}
function getInsurance(balance,interest,amount,payment){if(amount>=5000){return percentage((balance+interest),0.085)+percentage(payment,0.09)+percentage(1000,0.08)+percentage(1000,0.08);}else{return percentage((balance+interest),0.085)+percentage(payment,0.09)+percentage(400,0.08)+percentage(400,0.08);}}
function getPMT(ir,np,pv){var pmt,pvif,fv=0;if(ir===0){return-(pv+fv)/ np;}
pvif=Math.pow(1+ir,np);pmt=-ir*pv*(pvif+fv)/(pvif-1);return pmt;}
function getIRR(data){var min=0;var max=1;var guest;var NPV;do{guest=(min+max)/ 2;NPV=0;for(var j=0;j<data.length;j++){NPV+=data[j]/ Math.pow((1+guest),j);}
if(NPV>0){min=guest;}else{max=guest;}}while(Math.abs(NPV)>0.000001);return guest*100;}
function getMoney(value){return"U$ "+getFormattedNumber(value);}
function getFormattedNumber(value){return value.toString().replace(/\B(?=(\d{3})+(?!\d))/g,",");}
function toggleMoraTable(button){var table=document.getElementById("table-mora");var buttonAdd=document.getElementById("add");if(table.style.display=="none"){table.style.display="block";jQuery("#add").show();button.innerHTML="Ocultar otras opciones";populateTableMora(table);}else{if(table.style.display=="block"){table.style.display="none";jQuery("#add").hide();jQuery("#remove").hide();button.innerHTML="Mostrar otras opciones";}}}
function validateAmount(){var amount=getFloat("amount");if(amount<100||isNaN(amount)){return false;}
return true;}
function validateTerm(){var term=getInteger("term");if(term==0||isNaN(term)){return false;}
return true;}
function showErrorMesagge(minvalue,maxvalue,productIndex){if(minvalue==0&&maxvalue==0){jQuery("#message").text("El monto introducido es inv\u00E1lido.");}else{if(productIndex!=3){jQuery("#message").text("El monto debe estar comprendido entre "+setAmountFormat(minvalue)+" y "+setAmountFormat(maxvalue));}else{jQuery("#message").text("El monto debe ser hasta un máximo de "+setAmountFormat(maxvalue));}}
jQuery("#message").show();jQuery("#asterikamount").show();jQuery("#amount").focus();}
function hideErrorMesagge(){jQuery("#message").hide();jQuery("#asterikamount").hide();jQuery("#asterikterm").hide();}
function populateTableMora(){var table=document.getElementById("table-mora");var rows=table.rows.length;var index=rows;var pPal=0;var tasa=0;var tasaMora=0;var tasaDiaria=0;var dias=0;var mora=0;var arrmora=[];for(var i=1;i<rows;i++){row=table.rows[i];cols=table.rows[i].cells.length;for(var j=1;j<cols;j++){var col=row.cells[j];if(col.getElementsByClassName("ppal").length>0){pPal=getParseFloat(table.rows[1].cells[j].getElementsByClassName("ppal")[0].value);tasa=getParseFloat(table.rows[2].cells[j].getElementsByClassName("tasaAnual")[0].value);tasaMora=getTasaMora(tasa,table,j);tasaDiaria=getTasaDiariaMora(tasaMora,table,j);dias=getParseFloat(table.rows[5].cells[j].getElementsByClassName("diasMora")[0].value);mora=getMora(pPal,tasaDiaria,dias,table,j);arrmora.push(mora);}}}
getTotalMora(table,arrmora);}
function getTasaMora(tasa,table,cell){var tasaMora=parseFloat((tasa*0.5)/ 100).toFixed(2);table.rows[3].cells[cell].getElementsByClassName("tasaMora")[0].value=tasaMora;return tasaMora;}
function getTasaDiariaMora(tasa,table,cell){var tasaDiaria=parseFloat(tasa / 360).toFixed(7);table.rows[4].cells[cell].getElementsByClassName("tasaDiaria")[0].value=tasaDiaria;return tasaDiaria;}
function getMora(pPal,tasaDiaria,dias,table,cell){var mora=parseFloat(pPal*tasaDiaria*dias).toFixed(2);table.rows[6].cells[cell].getElementsByClassName("moraPagar")[0].value=mora;return mora;}
function getTotalMora(table,arrmora){var sum=0;for(var i=0;i<arrmora.length;i++){sum+=parseFloat(arrmora[i]);}
var indexRow=table.rows.length;var indexCell=table.rows[indexRow-1].cells.length;for(var i=1;i<indexCell;i++){table.rows[indexRow-1].cells[i].innerHTML="";}
table.rows[indexRow-1].cells[indexCell-1].style.fontWeight="bold";table.rows[indexRow-1].cells[indexCell-1].style.textAlign="right";table.rows[indexRow-1].cells[indexCell-1].innerHTML=getFormattedNumber(sum.toFixed(2));}
function addColumn(tblId){var tblHeadObj=document.getElementById(tblId).tHead;for(var h=0;h<tblHeadObj.rows.length;h++){var newTH=document.createElement("th");tblHeadObj.rows[h].appendChild(newTH);newTH.innerHTML="Cuota "+(tblHeadObj.rows[h].cells.length-1);}
var tblBodyObj=document.getElementById(tblId).tBodies[0];for(var i=0;i<tblBodyObj.rows.length;i++){var newCell=tblBodyObj.rows[i].insertCell(-1);if(i==0){newCell.innerHTML='<input class="ppal x-right x-input" type="text" value="0"/>';newCell.className="x-amount";}else{if(i==1){newCell.innerHTML='<input class="tasaAnual x-right x-input" type="text" value="0%"/>';newCell.className="x-amount";}else{if(i==2){newCell.innerHTML='<input type="text" disabled  class="tasaMora x-right x-input"/>';newCell.className="x-amount";}else{if(i==3){newCell.innerHTML='<input type="text" disabled class="tasaDiaria x-right x-input"/>';newCell.className="x-amount";}else{if(i==4){newCell.innerHTML='<input class="diasMora x-right x-input" type="text" value="0"/>';newCell.className="x-amount";}else{if(i==5){newCell.innerHTML='<input type="text" disabled class="moraPagar x-right x-input"/>';newCell.className="x-amount";}else{newCell.innerHTML="";newCell.className="x-amount";}}}}}}}
populateTableMora();jQuery("#remove").show();}
function deleteColumn(tblId){var allRows=document.getElementById(tblId).rows;for(var i=0;i<allRows.length;i++){if(allRows[i].cells.length>1){allRows[i].deleteCell(-1);}}
populateTableMora();var table=document.getElementById(tblId);if(table.rows[0].cells.length<=2){jQuery("#remove").hide();}}